# Generated by Django 4.2.2 on 2023-06-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productmodel_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (1, 'InProgress'), (2, 'Shipping'), (3, 'Delivered')], default=0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.ordermodel'),
        ),
    ]
