# Generated by Django 4.2.2 on 2023-06-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_productmodel_image_alter_ordermodel_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
